<?php

/**
 * Author: Jordi Roda, Ernest Pastor, Filip Velickovski, Magí Lluch-Ariet
 * Barcelona Digital Technology Centre, 2014
 *
 * Open Health Practice is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Open Health Practice is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file
 * Module file for ohp_pdf module.
 */

/**
 * Implements hook_menu().
 */
function ohp_pdf_menu() {
  $items['ohp/ohp_pdf/download/%/%'] = array(
    'title' => 'Download pdf',
    'description' => 'Generation of pdf files using TCPDF module.',
    'page callback' => 'ohp_pdf_download',
    'page arguments' => array(3,4),
    'access arguments' => array('use tcpdf example'),
    'file' => 'ohp_pdf.pages.inc',
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function ohp_pdf_theme($existing, $type, $theme, $path) {
  switch ($type) {
    case 'module':
      $themes = array(
        'ohp_pdf_basic_html' => array(
          'template' => 'tpl/ohp-pdf-basic-html',
          'variables' => array(
            'sex' => NULL,
            'cognom_nom' => NULL,
            'birthday' => NULL,
            'age' => NULL,
            'telf' => NULL,
            'cip' => NULL,
            'nhc' => NULL,
            'address' => NULL,
            'postcode' => NULL,
            'city' => NULL,
            'body' => NULL,
          ),
        ),
      );
      break;
  }
  return $themes;
}

/**
 * Implements hook_permission().
 */
function ohp_pdf_permission() {
  return array(
    'use tcpdf example' => array(
      'title' => t('Acces OHP pdf'),
      'description' => t('Allow users to access PDF pages'),
    ),
  );
}