<?php

/**
 * Author: Jordi Roda, Ernest Pastor, Filip Velickovski, Magí Lluch-Ariet  
 * Barcelona Digital Technology Centre, 2014 
 * 
 * Open Health Practice is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Open Health Practice is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file
 * Open Health Practice module.
 */

require_once 'ohp.utils.inc';

/**
 * Implements hook_user_login().
 */
function ohp_user_login(&$edit, $account) {
  
  $query = db_select('ohp_identification', 'n')
    ->fields('n', array('given_name', 'family_name'))
    ->condition('user_uid', $account->uid);
  
  $entries = $query->execute()->fetchAssoc();
  if (!empty($entries)) {
    $_SESSION['user_full_name'] = $entries["given_name"].' '.$entries["family_name"];
  }else{
    $_SESSION['user_full_name'] = '(sense identificar)';
  }
  $_SESSION['user_center'] = 'Hospital Clínic';
  $_SESSION['id_user'] = $account->uid;
  $_SESSION['case_bean'] = NULL;
  $_SESSION['admission_bean'] = NULL;
  drupal_goto('ohp/ohp_case');
}

/**
 * Implements hook_user_logout().
 */
function ohp_user_logout($account) {
  session_destroy();
  drupal_goto('user/login');
}

/**
 * Implements hook_forena_repos_alter().
 */
function ohp_forena_repos_alter(&$repos) {
  $m_path = drupal_get_path('module', 'ohp'); 
  $repos['ohp'] = array(
    'path' => $m_path . '/data',
    'title' => 'OHP repository',
    'access callback' => 'user_access',
    'user callback' => 'forena_current_user_id', 
    'data provider' => 'FrxDrupal', 
  );
}

/**
 * Implements hook_forena_report_directory().
 */
function ohp_forena_report_directory() {
  return drupal_get_path('module', 'ohp') . '/reports';
}
