<?php

/**
 * @file
 * A module that displays let you manage the treatment of deseases.
 */

require_once 'ohp.utils.inc';

/**
 * Implements hook_user_login().
 */
function ohp_user_login(&$edit, $account) {
  
  $query = db_select('ohp_identification', 'n')
    ->fields('n', array('given_name', 'family_name'))
    ->condition('user_uid', $account->uid);
  
  $entries = $query->execute()->fetchAssoc();
  if (!empty($entries)) {
    $_SESSION['user_full_name'] = $entries["given_name"].' '.$entries["family_name"];
  }else{
    $_SESSION['user_full_name'] = '';
  }
  $_SESSION['user_center'] = 'Hospital Clínic';
  $_SESSION['case_bean'] = NULL;
  $_SESSION['admission_bean'] = NULL;
}
