<?php

/**
 * Author: Jordi Roda, Ernest Pastor, Filip Velickovski, Magí Lluch-Ariet  
 * Barcelona Digital Technology Centre, 2014 
 * 
 * Open Health Practice is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Open Health Practice is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file
 * Module file for ohp_task module.
 */

/**
 * Implements hook_permission().
 */
function ohp_task_permission() {
  return array(
    'access ohp_task_assigned content' => array(
      'title' => t('Acces OHP tasks'),
      'description' => t('Allow users to access tasks assigned page'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function ohp_task_menu() {

  $items['ohp/ohp_task_assigned_active'] = array(
    'title' => 'Assignades pendents',
    'page callback' => 'ohp_task_assigned_active_page',
    'access arguments' => array('access ohp_task_assigned content'),
  );
  $items['ohp/ohp_task_assigned_done'] = array(
    'title' => 'Assignades finalitzades',
    'page callback' => 'ohp_task_assigned_done_page',
    'access arguments' => array('access ohp_task_assigned content'),
  );
  $items['ohp/ohp_task_insert'] = array(
    'title' => 'Nova tasca',
    'page callback' => 'ohp_task_insert_page',
    'access arguments' => array('access ohp_task_assigned content'),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

/**
 * Constructs a descriptive page.
 *
 * Our menu maps this function to the path 'ohp/ohp_task_insert'.
 */
function ohp_task_insert_page() {
  if(isset($_GET['id_case']) && isset($_GET['id_activity'])){
    $id_case = $_GET['id_case'];
    $code_activity = $_GET['id_activity'];
    $id_admission = NULL;
    if(!isset($_GET['id_admission']) || 
        $_GET['id_admission']==null || 
        $_GET['id_admission']==''){
      $id_admission = insert_admission($id_case);
    }else{
      $id_admission = $_GET['id_admission'];
    }
    $id_activity = NULL;
    if($code_activity=="#TASK:N261"){
      $id_activity = 2;
    }else if($code_activity=="#TASK:N253"){
      $id_activity = 1;
    }else{
      drupal_set_message("ERROR: code_activity");
      drupal_goto('ohp/ohp_case_main', array('query' => array('id_case' => $id_case)));
      return;
    }
    $id_task = insert_task($id_admission,$id_activity);
    if($id_activity == 2){
      update_task_role($id_task, 1);
    }
    unset($_SESSION['admission_bean']);
    drupal_goto('ohp/ohp_case_main', array('query' => array('id_case' => $id_case)));
  }
}

/**
 * Constructs a descriptive page.
 *
 * Our menu maps this function to the path 'ohp/ohp_task_assigned_active'.
 */
function ohp_task_assigned_active_page() {
  
  return ohp_task_assigned_page('ACTIVE',t('Pendents'));
}

/**
 * Constructs a descriptive page.
 *
 * Our menu maps this function to the path 'ohp/ohp_task_assigned_done'.
 */
function ohp_task_assigned_done_page() {
  
  return ohp_task_assigned_page('DONE',t('Finalitzades'));
}

function ohp_task_assigned_page($status,$subtitle_section) {
  
  $page_array = array();
  if(isset($_SESSION['id_user'])){
    $id_user = $_SESSION['id_user'];
    
    $result = get_user_tasks($id_user,$status);
  
    if($result->rowCount()>0){
  
      $items = array();
      $per_page = 6;
      // Initialize the pager
      $current_page = pager_default_initialize($result->rowCount(), $per_page);
  
      foreach ($result as $task) {
        $items[] = array(
          'data' => array(
            'id' => l(date('d/m/Y', $task->date), 'ohp/ohp_case_taskunit', array('query' => array('id_task' => $task->id_task, 'id_admission' => $task->id_admission, 'id_case' => $task->user_uid))),
            'item_description' => l($task->description, 'ohp/ohp_case_taskunit', array('query' => array('id_task' => $task->id_task, 'id_admission' => $task->id_admission, 'id_case' => $task->user_uid))),
            'bundle' => l(get_fullname ($task->given_name, $task->middle_name, $task->family_name, $task->family_name2), 'ohp/ohp_case_taskunit', array('query' => array('id_task' => $task->id_task, 'id_admission' => $task->id_admission, 'id_case' => $task->user_uid))),
          ),
        );
      }
      // Split your list into page sized chunks
      $chunks = array_chunk($items, $per_page, TRUE);
  
      // Create a render array ($page_array) which will be themed as a table with a
      // pager.
      $page_array['pager_table'] = array(
        '#theme' => 'table',
        '#header' => array(t('Data'), t('Tasca'), t('Pacient')),
        '#attributes' => array('class' => array('table_result','table_assigned'),),
        '#rows' => $chunks[$current_page],
        '#empty' => t('No hi ha elements per mostrar.'),
      );
  
      // Attach the pager theme.
      $page_array['pager_pager'] = array('#theme' => 'pager');
    }else{
      // There were no tasks. Tell the user.
      $content[] = array(
        '#type' => 'item',
        '#markup' => t('No hi ha elements per mostrar.'),
      );
      $page_array['table'] = $content;
    }
  }
  $page_container['main'] = array(
    '#theme' => 'ohp_task_assigned',
    '#page_content' => $page_array,
    '#subtitle_section' => $subtitle_section,
  );
  $page_container['main']['table_result']=$page_array;
  return $page_container;
}

/**
 * Process variables for ohp-task-assigned-layout.tpl.php
 *
 * @see ohp-task-assigned-layout.tpl.php
 */
function template_preprocess_ohp_task_assigned(&$variables) {
  $search_form = $variables['page_content'];
  $search_form_box = drupal_render($search_form);
  $variables['table_results'] = $search_form_box;
}

/**
 * Implements hook_theme().
 *
 * Defines the theming capabilities provided by this module.
 */
function ohp_task_theme() {
  return array(
    'ohp_task_assigned'  => array(
      'template' => 'tpl/ohp-task-assigned-layout',
      'variables' => array(
        'subtitle_section' => NULL,
        'page_content' => NULL,
      ),
    ),
  );
}

